# Generated by Django 3.2.8 on 2022-05-30 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='noname', max_length=16)),
                ('intro', models.CharField(blank=True, default='Intro not entered', max_length=512, null=True)),
                ('imguploaded', models.IntegerField(default=0, null=True)),
                ('likes', models.IntegerField(default=0, null=True)),
                ('profile_pic', models.ImageField(default='default.png', null=True, upload_to='member/')),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
