# Generated by Django 3.2.8 on 2022-02-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
