# Generated by Django 3.2.8 on 2022-04-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_member_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='noname', max_length=16, null=True),
        ),
    ]
