# Generated by Django 3.2.8 on 2022-02-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
