# Generated by Django 3.2.8 on 2022-02-07 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_rename_member_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Member',
        ),
    ]
