# Generated by Django 3.2.8 on 2022-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_member_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(blank=True, default='noname', max_length=16),
        ),
    ]
