# Generated by Django 3.2.8 on 2022-02-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_member_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
    ]
