# Generated by Django 3.2.8 on 2022-03-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_comment_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='photo',
        ),
    ]
