# Generated by Django 3.2.8 on 2022-04-26 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_remove_comment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='photos', to='memes.Tag'),
        ),
    ]
