# Generated by Django 3.2.8 on 2022-05-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_alter_photo_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violence', models.BooleanField()),
                ('pornography', models.BooleanField()),
                ('personalattacks', models.BooleanField()),
                ('hurteyes', models.BooleanField()),
                ('Jackson', models.BooleanField()),
                ('content', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
