# Generated by Django 3.2.8 on 2022-05-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0009_alter_report_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='Jackson',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='content',
            field=models.TextField(blank=True, default='Content not entered', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='hurteyes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='personalattacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='pornography',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='violence',
            field=models.BooleanField(default=False),
        ),
    ]
